#!/usr/bin/env python
# by duo July 2018

from moviepy.editor import ImageSequenceClip
import argparse


def main():
    parser = argparse.ArgumentParser(description='Create session video.')
    parser.add_argument(
        '--imgs',
        type=str,
        default='/tmp/amanajeMovieImages/',
        help='Path to image folder. The video will be created from these images.'
    )
    parser.add_argument(
        '--out',
        type=str,
        default='/home/duo/Vídeos/',
        help='The video will be created on this path.'
    )
    parser.add_argument(
        '--fps',
        type=int,
        default=24,
        help='FPS (Frames per second) settfromg for the video.'
    )
    args = parser.parse_args()

    clip = ImageSequenceClip(args.imgs, fps=args.fps)
    video_file = args.out + 'amanaje.mp4'
    print("Creating video {}, FPS={}".format(video_file, args.fps))
    clip.write_videofile(video_file)


if __name__ == '__main__':
    main()
