#!/usr/bin/env python
# by duo Dec 2017

import tkinter
import cv2
import time
import numpy as np
import os
import argparse
from datetime import datetime
import shutil
from PIL import Image, ImageTk

global drawing
global bigframe
global bigmask


def mouseDragged(event):
  global bigframe
  cv2.circle(bigframe,(event.x, event.y), 6, (255, 0, 0), -1)
#  for i in range(12):
#    for j in range(8):
#     bigframe[event.y+j, event.x+i] = (255, 0, 0)

width, height = 320, 240
cam = cv2.VideoCapture(-1)
cam.set(cv2.CAP_PROP_FRAME_WIDTH, width)
cam.set(cv2.CAP_PROP_FRAME_HEIGHT, height)

window = tkinter.Tk()
window.title('Amanajé')
window.bind('<Escape>', lambda e: window.quit())

window.bind("<B1-Motion>", mouseDragged)

canvas = tkinter.Label(window)
canvas.pack()
drawing = False
txt = ' '
bigframe = np.ones((700, 1280, 3), np.uint8)
bigframe = bigframe * 255
bigmask = np.zeros((700, 1280), int)

def show_webcam():
  global drawing
  global bigframe
  global bigmask
  _, frame = cam.read()
  frame = cv2.flip(frame, 1)
  x = window.winfo_pointerx() - window.winfo_rootx()
  y = window.winfo_pointery() - window.winfo_rooty()
  txt = 'Mouse : (' + str(x) + ', ' + str(y) + ')'
  cv2.putText(frame, txt, (int(width*0.3), int(height*0.05)), cv2.FONT_HERSHEY_TRIPLEX, 0.6, (255, 0, 0), 1, cv2.LINE_AA)
  txt2 = '' + str(frame.shape)
  cv2.putText(frame, txt2, (int(width*0.3), int(height*0.85)), cv2.FONT_HERSHEY_TRIPLEX, 0.6, (255, 0, 0), 1, cv2.LINE_AA)
  bigframe[700-240:, 1280-320:,:] = frame
  cv2image = cv2.cvtColor(bigframe, cv2.COLOR_BGR2RGBA)
  img = Image.fromarray(cv2image)
  imgtk = ImageTk.PhotoImage(image=img)
  canvas.imgtk = imgtk
  canvas.configure(image=imgtk)
  canvas.after(10, show_webcam)


def toggleDraw():
  global drawing
  drawing = not drawing

btn_snapshot=tkinter.Button(window, text="Draw", width=50, command=toggleDraw)
btn_snapshot.pack(anchor=tkinter.CENTER, expand=False)

show_webcam()
window.mainloop()

